version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
    env_file:
      - .env.example
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
